# XOR

In [1]:
import pandas as pd
from sklearn import svm, metrics

In [2]:
xor_data = [
    [0,0,0],
    [0,1,1],
    [1,0,1],
    [1,1,0]
]

#주어진 데이터를 분리(학습데이터와 레이블을 분리)
training_data = []
label = []

In [3]:
for row in xor_data:
    p = row[0]
    q = row[1]
    result = row[2]
    
    training_data.append([p,q]) #Ridge형태로 넣어주기
    label.append(result)

In [4]:
clf = svm.SVC()

In [5]:
clf.fit(training_data, label)

pre = clf.predict(training_data)

print('예측결과:', pre)

예측결과: [0 1 1 0]


In [6]:
ok = 0; total = 0

for idx, answer in enumerate(label):
    P = pre[idx]
    if P == answer: ok += 1
    total += 1

print('정확도:',ok,'/',total,'=',ok/total)

정확도: 4 / 4 = 1.0


In [7]:
xor_df = pd.DataFrame(xor_data)

trainingData = xor_df.loc[:,0:1]
label = xor_df.loc[:,2]

clf = svm.SVC()
clf.fit(trainingData,label)

pre = clf.predict(trainingData)

accuracy = metrics.accuracy_score(label, pre)

print('정확도:',accuracy)

정확도: 1.0


# Scipy

In [8]:
import numpy as np
from scipy import sparse

In [9]:
h1 = np.eye(4,dtype=int)
print('Numpy 배열:\n{}'.format(h1))
sparse_matrix = sparse.csr_matrix(h1)
print('Scipy의 CSR행렬: \n{}'.format(sparse_matrix))
print('------------------')
h2 = np.eye(5, k=-1, dtype=int)
sparse_matrix = sparse.csr_matrix(h2)
print('Scipy의 CSR행렬: \n{}'.format(sparse_matrix))

Numpy 배열:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Scipy의 CSR행렬: 
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1
------------------
Scipy의 CSR행렬: 
  (1, 0)	1
  (2, 1)	1
  (3, 2)	1
  (4, 3)	1


In [10]:
h3 = np.arange(16).reshape(4,4)
x = np.diag(h3)
print(x)
y = np.diag(np.diag(h3))
print('------------------\n{}'.format(y))
print('------------------')
sparse_matrix = sparse.csr_matrix(y)
print('Scipy의 CSR행렬: \n{}'.format(sparse_matrix))

[ 0  5 10 15]
------------------
[[ 0  0  0  0]
 [ 0  5  0  0]
 [ 0  0 10  0]
 [ 0  0  0 15]]
------------------
Scipy의 CSR행렬: 
  (1, 1)	5
  (2, 2)	10
  (3, 3)	15


In [11]:
data = np.ones(4)
print(data)

row_indices = np.arange(4)
col_indices = np.arange(4)

eye_coo = sparse.coo_matrix((data,(row_indices,col_indices)))
print('COO 표현: \n{}'.format(eye_coo))

[1. 1. 1. 1.]
COO 표현: 
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
